// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9mFgoN5iH_8nk-kqo6Ifx9ZA_fy-UUAw',
    appId: '1:800852827950:web:a9f20c6e55f8a5989064bf',
    messagingSenderId: '800852827950',
    projectId: 'digital-certification-repo',
    authDomain: 'digital-certification-repo.firebaseapp.com',
    storageBucket: 'digital-certification-repo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABB9By3vn4l60iPEhMYFYlCFkmCB_61Ug',
    appId: '1:800852827950:android:15a53d5b5238845a9064bf',
    messagingSenderId: '800852827950',
    projectId: 'digital-certification-repo',
    storageBucket: 'digital-certification-repo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJgCKo3gME30KqX3HfK6IctJCK0ehR6kY',
    appId: '1:800852827950:ios:73707c1daeb8a7e69064bf',
    messagingSenderId: '800852827950',
    projectId: 'digital-certification-repo',
    storageBucket: 'digital-certification-repo.firebasestorage.app',
    iosBundleId: 'com.example.digitalCert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJgCKo3gME30KqX3HfK6IctJCK0ehR6kY',
    appId: '1:800852827950:ios:73707c1daeb8a7e69064bf',
    messagingSenderId: '800852827950',
    projectId: 'digital-certification-repo',
    storageBucket: 'digital-certification-repo.firebasestorage.app',
    iosBundleId: 'com.example.digitalCert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9mFgoN5iH_8nk-kqo6Ifx9ZA_fy-UUAw',
    appId: '1:800852827950:web:d39a95036d7e0f779064bf',
    messagingSenderId: '800852827950',
    projectId: 'digital-certification-repo',
    authDomain: 'digital-certification-repo.firebaseapp.com',
    storageBucket: 'digital-certification-repo.firebasestorage.app',
  );
}
